# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://rochelleshen.com
title: Rochelle Shen
email: aberayshen@gmail.com
author: Rochelle Shen
description: >  "Rochelle Shen's Blog and Homepage"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://www.facebook.com/Rochelleyinyi
  - title: github
    url: https://github.com/RochelleShen
  - title: linkedin
    url: https://www.linkedin.com/in/rcshen
